# Generated by Django 3.2.21 on 2023-09-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='ANJANA'),
            preserve_default=False,
        ),
    ]
